---
- name: Install Jenkins
  hosts:  all
  gather_facts: false
  become: true
  vars_files:
    - ../vars.yml
  tasks:
    - name: Task Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Task Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
          
    - name: ensure the jenkins apt repository key is installed
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
      become: yes

    - name: ensure the repository is configured
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
      become: yes

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: yes

    - name: ensure jenkins is running
      service: name=jenkins state=started

    - name: Download and install Jenkins keyring
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null &&
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    
    - name: Create initialization scripts directory
      file: path=/var/lib/jenkins/init.groovy.d
            state=directory
            owner=jenkins
            group=jenkins
            mode=0775

    - name: Add initialization script to setup basic security
      template: src=../security.groovy.j2
            dest=/var/lib/jenkins/init.groovy.d/security.groovy

    - name: Restart Jenkins
      service: name=jenkins state=restarted

    - name: Install plugin
      community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: "{{ jenkins_admin_username }}"
        url_password: "{{ jenkins_admin_username }}"
        url: http://localhost:8080
        timeout: "10000"
        state: latest
      with_items:  
        - ace-editor
        - ant
        - antisamy-markup-formatter
        - apache-httpcomponents-client-4-api
        - bootstrap4-api
        - bootstrap5-api
        - bouncycastle-api
        - branch-api
        - build-timeout
        - caffeine-api
        - checks-api
        - cloudbees-folder
        - command-launcher
        - credentials
        - credentials-binding
        - display-url-api
        - durable-task
        - echarts-api
        - email-ext
        - font-awesome-api
        - git
        - git-client
        - git-server
        - github
        - github-api
        - github-branch-source
        - gradle
        - handlebars
        - jackson2-api
        - jaxb
        - jdk-tool
        - jjwt-api
        - jquery3-api
        - jsch
        - junit
        - ldap
        - lockable-resources
        - mailer
        - matrix-auth
        - matrix-project
        - momentjs
        - okhttp-api
        - pam-auth
        - pipeline-build-step
        - pipeline-github-lib
        - pipeline-graph-analysis
        - pipeline-input-step
        - pipeline-milestone-step
        - pipeline-model-api
        - pipeline-model-definition
        - pipeline-model-extensions
        - pipeline-rest-api
        - pipeline-stage-step
        - pipeline-stage-tags-metadata
        - pipeline-stage-view
        - plain-credentials
        - plugin-util-api
        - popper-api
        - popper2-api
        - resource-disposer
        - scm-api
        - script-security
        - snakeyaml-api
        - ssh-credentials
        - ssh-slaves
        - sshd
        - structs
        - timestamper
        - token-macro
        - trilead-api
        - workflow-aggregator
        - workflow-api
        - workflow-basic-steps
        - workflow-cps
        - workflow-cps-global-lib
        - workflow-durable-task-step
        - workflow-job
        - workflow-multibranch
        - workflow-scm-step
        - workflow-step-api
        - workflow-support
        - ws-cleanup
        
    - name: "Turn off Jenkins setup wizard"
      lineinfile:
          dest: /etc/init.d/jenkins
          regexp: '^JAVA_ARGS='
          line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
          insertbefore: '^DAEMON_ARGS='

    - name: Restart Jenkins
      service: name=jenkins state=restarted

    # - name: Install Jenkins plugins
    #   jenkins_plugin:
    #     name: kubernetes
    #     state: present
    #     url: "http://3.231.56.123:8080/"
    #     url_username: "{{ jenkins_admin_username }}"
    #     url_password: "{{ jenkins_admin_password }}"