FROM mysql:5.6.51
# docker-entrypoint-initdb.d directory in the MySQL container that is automatically executed during the initialization of the container
ADD BucketList.sql /docker-entrypoint-initdb.d
